// <auto-generated />
namespace SOD.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class PostMigration10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostMigration10));
        
        string IMigrationMetadata.Id
        {
            get { return "201609020708553_PostMigration10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
